function colornames=getnames
colornames={'indian red';
    'crimson';
    'very light pink';
    'light pink';
    'light pink';
    'dull pink';
    'dull dark pink';
    'light pink';
    'pink';
    'pink';
    'dull pink';
    'dull dark pink';
    'deep pink';
    'pink';
    'pink';
    'deep pink';
    'dark deep pink';
    'off-white';
    'very pale lavender';
    'pale lavender';
    'dull lavender';
    'violet red';
    'violet red';
    'deep violet red';
    'dark deep violet red';
    'hot pink';
    'hot pink';
    'hot pink';
    'dark hot pink';
    'dark dull pink';
    'raspberry';
    'deep pink';
    'deep pink';
    'deep pink';
    'dark deep maroon';
    'light maroon';
    'maroon';
    'maroon';
    'dark maroon';
    'medium violet red';
    'violetred';
    'light orchid';
    'orchid';
    'orchid';
    'orchid';
    'dark orchid';
    'light thistle';
    'thistle';
    'thistle';
    'dull thistle';
    'dark dull thistle';
    'light plum';
    'plum';
    'plum';
    'dark dull plum';
    'light plum';
    'pink-violet';
    'fuchsia';
    'magenta';
    'magenta';
    'deep purple';
    'purple';
    'medium orchid';
    'medium orchid';
    'medium orchid';
    'dull medium orchid';
    'dark medium orchid';
    'dark violet';
    'dark orchid';
    'dark orchid';
    'dark orchid';
    'dark orchid';
    'very dark orchid';
    'indigo';
    'blue violet';
    'purple';
    'purple';
    'purple';
    'dark purple';
    'pale purple';
    'pale purple';
    'pale purple';
    'pale purple';
    'dark pale purple';
    'dark slate blue';
    'light slate blue';
    'medium slate blue';
    'slate blue';
    'slate blue';
    'slate blue';
    'slate blue';
    'dark slate blue';
    'ghost-white';
    'very faint lavender';
    'blue';
    'blue';
    'medium blue';
    'dark blue';
    'navy';
    'midnight blue';
    'cobalt';
    'royal blue';
    'bright royal blue';
    'royal blue';
    'royal blue';
    'dark royal blue';
    'cornflower blue';
    'light steel blue';
    'very light steel blue';
    'light steel blue';
    'steel blue';
    'dull dark steel blue';
    'slate gray';
    'slate gray';
    'very light slate gray';
    'light slate gray';
    'light slate gray';
    'medium slate gray';
    'dodger blue';
    'dodger blue';
    'dodger blue';
    'dark dodger blue';
    'very faint blue';
    'steel blue';
    'steel blue';
    'steel blue';
    'steel blue';
    'dark steel blue';
    'light sky blue';
    'light sky blue';
    'light sky blue';
    'dull sky blue';
    'dark dull sky blue';
    'sky blue';
    'sky blue';
    'sky blue';
    'steel blue';
    'sky blue';
    'bright deep sky blue';
    'deep sky blue';
    'deep sky blue';
    'dark deep sky blue';
    'peacock';
    'light blue';
    'light blue';
    'light blue';
    'dull light blue';
    'dull medium blue';
    'powder blue';
    'cadet blue';
    'cadet blue';
    'cadet blue';
    'dark cadet blue';
    'turquoise';
    'turquoise';
    'turquoise';
    'dark turquoise';
    'cadet blue';
    'dark turquoise';
    'very faint azure';
    'azure';
    'dull azure';
    'dark dull azure';
    'light cyan';
    'light cyan';
    'dull light cyan';
    'dull cyan';
    'pale turquoise';
    'pale turquoise';
    'pale turquoise';
    'dark pale turquoise';
    'very dark turquoise';
    'light turquoise';
    'turquoise';
    'turquoise';
    'dull turquoise';
    'bright cyan';
    'cyan';
    'cyan';
    'dark cyan';
    'dark teal';
    'medium turquoise';
    'manganese blue';
    'manganese blue';
    'turquoise';
    'cold grey';
    'turquoise green';
    'aquamarine';
    'aquamarine';
    'aquamarine';
    'dark aquamarine';
    'medium spring green';
    'mint cream';
    'bright spring green';
    'spring green';
    'spring green';
    'dark spring green';
    'medium sea green';
    'bright sea green';
    'sea green';
    'dull sea green';
    'dark dull sea green';
    'emerald green';
    'mint';
    'cobalt green';
    'very faint honeydew';
    'honeydew';
    'grayish honeydew';
    'greenish gray';
    'light sea green';
    'dark sea green';
    'light sea green';
    'sea green';
    'dark sea green';
    'pale green';
    'pale green';
    'pale green';
    'dull green';
    'dark dull green';
    'lime green';
    'forest green';
    'lime green';
    'bright green';
    'green';
    'green';
    'dark green';
    'dark forest green';
    'sap green';
    'lawn green';
    'bright chartreuse';
    'chartreuse';
    'dark chartreuse';
    'dark chartreuse';
    'green-yellow';
    'pale olive green';
    'light olive green';
    'olive green';
    'olive green';
    'dark olive green';
    'light olive drab';
    'olive drab';
    'olive drab';
    'yellow-green';
    'olive drab';
    'pale ivory';
    'ivory';
    'ivory';
    'ivory';
    'beige';
    'very faint yellow';
    'light yellow';
    'light gray';
    'medium gray';
    'extremely faint goldenrod';
    'yellow';
    'yellow';
    'greenish yellow';
    'olive green';
    'warm grey';
    'olive green';
    'dark khaki';
    'light khaki';
    'khaki';
    'khaki';
    'dark khaki';
    'khaki';
    'pale golden rod';
    'lemon chiffon';
    'lemon chiffon';
    'dull lemon chiffon';
    'medium gray';
    'light goldenrod';
    'light goldenrod';
    'dull goldenrod';
    'dark goldenrod';
    'banana';
    'gold';
    'gold';
    'gold';
    'dark gold';
    'light beige';
    'light french gray';
    'light gray';
    'medium gray';
    'goldenrod';
    'goldenrod';
    'goldenrod';
    'goldenrod';
    'dark goldenrod';
    'dark goldenrod';
    'goldenrod';
    'dark goldenrod';
    'dark goldenrod';
    'dark goldenrod';
    'bright orange';
    'orange';
    'orange';
    'dark orange';
    'floral white';
    'off-white';
    'flesh';
    'pale flesh';
    'flesh';
    'taupe';
    'dark taupe';
    'moccasin';
    'papaya whip';
    'blanched almond';
    'navajo white';
    'navajo white';
    'dark navajo white';
    'very dark navajo white';
    'eggshell white';
    'tan';
    'brick';
    'cadmium yellow';
    'antique white';
    'antique white';
    'antique white';
    'dark antique white';
    'medium french gray';
    'burlywood';
    'burlywood';
    'burlywood';
    'burlywood';
    'dark burlywood';
    'bisque';
    'bisque';
    'french gray';
    'dark french gray';
    'melon';
    'carrot';
    'orange';
    'orange';
    'dark orange';
    'dark orange';
    'brown';
    'orange';
    'tan';
    'tan';
    'dark tan';
    'brown';
    'linen';
    'peachpuff';
    'peachpuff';
    'dull peachpuff';
    'dark dull peachpuff';
    'faint seashell';
    'seashell';
    'light gray';
    'medium gray';
    'sandy brown';
    'raw sienna';
    'burnt orange';
    'burnt orange';
    'burnt orange';
    'burnt orange';
    'chocolate';
    'ivory black';
    'flesh';
    'cadmium orange';
    'burnt sienna';
    'orange sienna';
    'sienna';
    'sienna';
    'sienna';
    'sienna';
    'light salmon';
    'light salmon';
    'light salmon';
    'dull medium salmon';
    'coral';
    'orange-red';
    'orange-red';
    'orange-red';
    'dark orange-red';
    'dark sepia';
    'pale salmon';
    'salmon';
    'salmon';
    'salmon';
    'dull reddish brown';
    'coral';
    'coral';
    'coral';
    'dark coral';
    'burnt umber';
    'tomato';
    'tomato';
    'tomato';
    'dark tomato';
    'salmon';
    'misty rose';
    'misty rose';
    'misty rose';
    'medium reddish gray';
    'snow white';
    'very light gray';
    'light gray';
    'medium gray';
    'dull rosy brown';
    'dull rosy brown';
    'dull rosy brown';
    'dull rosy brown';
    'dark rosy brown';
    'light coral';
    'indian red';
    'indian red';
    'indian red';
    'dark indian red';
    'indian red';
    'dull red';
    'dull red';
    'dull red';
    'dull red';
    'dark dull red';
    'red';
    'red';
    'red';
    'red';
    'dark red';
    'bright red';
    'bright red';
    'bright red';
    'dark bright red';
    'maroon';
    'beet purple';
    'slate blue';
    'light blue';
    'teal';
    'chartreuse';
    'olive drab';
    'bright gray';
    'dull salmon';
    'black';
    'charcoal gray';
    'dark gray';
    'medium gray';
    'light gray';
    'very light gray';
    'very faint gray';
    'white';
    'dark cornflower blue';
    'really dark red';
    'really dark green';
    'really dark blue';
    'really dark yellow';
    'really dark purple';
    'really dark turquoise';
    'dark dull brown';
    'violet';
    'magenta';
    'dark dull purple';
    'dark dull green';
    'dull green';
    'dark forest green';
    'very dull sea green';
    'very dark dull yellow';
    'puke yellow';
    'puke green'};
